### ISSUE TITLE
Documentation issue for `subscription` directive

### ISSUE THREAD

**Issue by andreloeffelmann** [neo4j/docs-graphql#153]
**Describe the bug**
The documentation for `subscription` directive ([here](https://neo4j.com/docs/graphql/current/directives/schema-configuration/type-configuration/#_subscription)) seems not to be up to date.
At least with `@neo4j/graphql@5.4.2` the field within the directive to determine the several `SubscriptionFields` is not called `operations` but `events`

**Comment by neo4j-team-graphql** [comment]
Many thanks for raising this bug report @andreloeffelmann. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

Please ensure that you've provided the necessary information for a minimal reproduction, including but not limited to:
* Type definitions
* Resolvers
* Query and/or Mutation (or multiple) needed to reproduce

If you have a support agreement with Neo4j, please link this GitHub issue to a new or existing Zendesk ticket.

Thanks again! :pray:

**Comment by MacondoExpress** [comment]
You're right, thank you for having raised it, we will fix that soon!
